---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.annotations.role_arn }}

